# Generated by Django 4.2 on 2023-04-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LinkMap",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("redirects_to", models.URLField()),
                ("short_url", models.CharField(max_length=15, unique=True)),
                ("times_followed", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
